### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Acromion1754** [ldsz/plugin.audio.spotify#12]
hi, installed but I cannot login.
here's my log:
2021-05-17 15:57:38.027 T:4735     INFO <general>: plugin.audio.spotify --> b'retrieving token...'
2021-05-17 15:57:38.032 T:4735     INFO <general>: plugin.audio.spotify --> b'Retrieving auth token....'
2021-05-17 15:57:38.076 T:4735     INFO <general>: plugin.audio.spotify --> b'request_token_spotty stdout: b"thread \'main\' panicked at \'called `Option::unwrap()` on a `None` value\', libcore/option.rs:355:21\\nnote: Run with `RUST_BACKTRACE=1` for a backtrace.\\n"'
2021-05-17 15:57:43.115 T:4735     INFO <general>: plugin.audio.spotify --> b"request_token_spotty stdout: b''"
2021-05-17 15:57:43.116 T:4735     INFO <general>: plugin.audio.spotify --> b"Couldn't request authentication token. Username/password error ? If you're using a facebook account with Spotify, make sure to generate a device account/password in the Spotify accountdetails."
2021-05-17 15:57:48.123 T:4735     INFO <general>: plugin.audio.spotify --> b'retrieving token...'
2021-05-17 15:57:48.127 T:4735     INFO <general>: plugin.audio.spotify --> b'Retrieving auth token....'
2021-05-17 15:57:48.173 T:4735     INFO <general>: plugin.audio.spotify --> b'request_token_spotty stdout: b"thread \'main\' panicked at \'called `Option::unwrap()` on a `None` value\', libcore/option.rs:355:21\\nnote: Run with `RUST_BACKTRACE=1` for a backtrace.\\n"'

**Comment by mxkle** [comment]
hi,

i have the same problem at the moment. i double checked my credentials so i am sure they are correct. here is a part of the kodi.log file:

```
2022-09-27 17:03:51.042 T:5920     INFO <general>: plugin.audio.spotify --> b'Retrieving auth token....'
2022-09-27 17:03:51.142 T:5920     INFO <general>: plugin.audio.spotify --> b'request_token_spotty stdout: b"thread \'main\' panicked at \'called `Option::unwrap()` on a `None` value\', src/libcore/option.rs:345:
21\\nnote: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n"'
2022-09-27 17:03:51.143 T:5920    DEBUG <CAddonSettings[plugin.audio.spotify]>: trying to load setting definitions from old format...
2022-09-27 17:03:56.144 T:6156    ERROR <general>: Exception in thread
2022-09-27 17:03:56.144 T:6156    ERROR <general>: Thread-30 (kill_on_timeout)
2022-09-27 17:03:56.144 T:6156    ERROR <general>: :

2022-09-27 17:03:56.144 T:6156    ERROR <general>: Traceback (most recent call last):

2022-09-27 17:03:56.144 T:6156    ERROR <general>:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

2022-09-27 17:03:56.145 T:6156    ERROR <general>:
2022-09-27 17:03:56.145 T:6156    ERROR <general>: self.run()
2022-09-27 17:03:56.145 T:6156    ERROR <general>:

2022-09-27 17:03:56.145 T:6156    ERROR <general>:   File "/usr/lib/python3.10/threading.py", line 953, in run

2022-09-27 17:03:56.146 T:6156    ERROR <general>:
2022-09-27 17:03:56.146 T:6156    ERROR <general>: self._target(*self._args, **self._kwargs)
2022-09-27 17:03:56.146 T:6156    ERROR <general>:

2022-09-27 17:03:56.146 T:6156    ERROR <general>:   File "/var/lib/kodi/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 107, in kill_on_timeout

2022-09-27 17:03:56.146 T:6156    ERROR <general>:
2022-09-27 17:03:56.146 T:6156    ERROR <general>: proc.kill()
2022-09-27 17:03:56.146 T:6156    ERROR <general>:

2022-09-27 17:03:56.146 T:6156    ERROR <general>: AttributeError
2022-09-27 17:03:56.146 T:6156    ERROR <general>: :
2022-09-27 17:03:56.146 T:6156    ERROR <general>: 'Spotty' object has no attribute 'kill'
2022-09-27 17:03:56.146 T:6156    ERROR <general>:

2022-09-27 17:03:56.146 T:6156    DEBUG <general>: .
2022-09-27 17:04:00.730 T:5886    DEBUG <general>: Skipped 1 duplicate messages..
2022-09-27 17:04:00.730 T:5886    DEBUG <general>: Sink changed
2022-09-27 17:04:01.228 T:5920     INFO <general>: plugin.audio.spotify --> b'request_token_spotty stdout: b\'thread \\\'main\\\' panicked at \\\'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("failed to lookup address information: Try again") }\\\', src/libcore/result.rs:997:5\\nnote: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\''
2022-09-27 17:04:01.228 T:5920     INFO <general>: plugin.audio.spotify --> b"Couldn't request authentication token. Username/password error ? If you're using a facebook account with Spotify, make sure to generate a device account/password in the Spotify accountdetails."
2022-09-27 17:04:01.229 T:6166     INFO <general>: plugin.audio.spotify --> b'Start Spotify Connect Daemon'
2022-09-27 17:04:01.229 T:6166     INFO <general>: plugin.audio.spotify --> b'trying AP Port 443'
```
i also tried to use the spotify username instead of my email, but no luck with that. also its a standalone account, no facebook.

i am using arch linux, kodi version 19.4.0

any help appreciated :)

**Comment by vguttmann** [comment]
Do you have Librespot installed/active as well? For me, while I had Librespot installed and active, Spotify would refuse to even launch.

**Comment by mxkle** [comment]
I had spotifyd installed from the AUR. I removed it now for testing purposes but it didnt change anything.
Same error as before.

**Comment by salvq** [comment]
Same issue here, 100% sure credential are fine but not able to login, see https://github.com/ldsz/plugin.audio.spotify/issues/22

**Comment by vguttmann** [comment]
@salvq Do you have Librespot installed and activated?

**Comment by salvq** [comment]
No, I do not have enabled or even installed, I am using CoreELEC 19.4

I can verify and debug spotify by running command `spotty-hf` from SSH but not sure about the right parameters and verbose.

Can you help here ?

Thanks

**EDIT: I was able to get the plugin working by installing Librespot, run the librespot then disable it and then enable plugin.audio.spotify but still time to time I am getting error window about credential.**

**Comment by bratekarate** [comment]
Is it true that spotify premium is required as indicated [here](https://github.com/ldsz/plugin.audio.spotify/issues/23#issuecomment-1269221214)?

If yes, this information should definitely be included in this issue and also in the README.md. It's quite frustrating otherwise, as this is a vital part that MUST be documented!
