### ISSUE TITLE
Addon crashes when playing music

### ISSUE THREAD

**Issue by theelichtje** [ldsz/plugin.audio.spotify#21]
Whenever i try to play music through the addon, or stream from my phone (it doesn't even show up on my phone) the addon crashes, with the below log:

2021-08-28 17:44:12.667 T:6936    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>=' not supported between instances of 'tuple' and 'int'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\spotipy\client.py", line 121, in _internal_call
                                                       r.raise_for_status()
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/play
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\plugin_content.py", line 55, in __init__
                                                       eval(action)()
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\plugin_content.py", line 292, in connect_playback
                                                       self.sp.start_playback(context_uri=context_uri, offset=offset)
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\spotipy\client.py", line 972, in start_playback
                                                       return self._put(self._append_device_id("me/player/play", device_id), payload=data)
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\spotipy\client.py", line 190, in _put
                                                       return self._internal_call('PUT', url, payload, kwargs)
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\spotipy\client.py", line 124, in _internal_call
                                                       raise SpotifyException(r.status_code,
                                                   spotipy.client.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play:
                                                    Player command failed: No active device found
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\plugin.py", line 14, in <module>
                                                       PluginContent()
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\plugin_content.py", line 62, in __init__
                                                       log_exception(__name__, exc)
                                                     File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\utils.py", line 90, in log_exception
                                                       log_msg(format_exc(sys.exc_info()), xbmc.LOGDEBUG)
                                                     File "C:\Program Files\Kodi\system\python\Lib\traceback.py", line 167, in format_exc
                                                       return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
                                                     File "C:\Program Files\Kodi\system\python\Lib\traceback.py", line 120, in format_exception
                                                       return list(TracebackException(
                                                     File "C:\Program Files\Kodi\system\python\Lib\traceback.py", line 493, in __init__
                                                       context = TracebackException(
                                                     File "C:\Program Files\Kodi\system\python\Lib\traceback.py", line 509, in __init__
                                                       self.stack = StackSummary.extract(
                                                     File "C:\Program Files\Kodi\system\python\Lib\traceback.py", line 340, in extract
                                                       if limit >= 0:
                                                   TypeError: '>=' not supported between instances of 'tuple' and 'int'
                                                   -->End of Python script error report<--
                                                   
2021-08-28 17:44:12.892 T:6936     INFO <general>: Python interpreter stopped

I'm running Kodi 19.1 on Windows 10.

**Comment by alexiswatson** [comment]
I'm able to reproduce this issue on a Gen1 Fire Stick 4K, running Kodi 19.4.
